#!/bin/sh
file="$HOME/.sensitive/bookmarks"
bookmark="$(xclip -o)"

if grep -q "^$bookmark$" "$file"; then
	notify-send "Bookmark already exists"
else
	notify-send "Bookmark added: $bookmark"
	echo "$bookmark" >> "$file"
fi


