#!/bin/bash
# Function to handle errors
handle_error() {
    local exit_code=$1
    local message=$2
    echo "Error: $message"
    exit "$exit_code"
}

# Usage
if [ $# -lt 0 ]; then
    handle_error 1 "Usage: $0 <opt: loop>"
fi

echo "this is the new version btw" >&2

crosslink_all_files() {
  for file in $(find "$OBSIDIANDIRECTORY" -type f); do
    crosslink "$file"
    for link in $(getlinks "$file" | uniq); do
      escapedlink=$(sed 's/\[/\\\[/g; s/\]/\\\]/g;' <<< $link)
      dedupe "$escapedlink" "$file" #&& echo "deduped $link in $file" >&2
    done
  done
}

crosslink_all_files

if [ "$1" == "loop" ];
then
  # Wait for a write operation on any .md file in the directory
  inotifywait -e modify -m "$OBSIDIANDIRECTORY/.obsidian/workspace.json" -q | while read file; do
    crosslink_all_files
  done
fi
