#!/bin/bash
# Function to handle errors
handle_error() {
    local exit_code=$1
    local message=$2
    echo "Error: $message"
    exit "$exit_code"
}

# Usage
if [ $# -lt 0 ]; then
    handle_error 1 "Usage: $0 <>"
fi

for file in $(find "$OBSIDIANDIRECTORY" -type f -name "*.md"); do
  crosslink "$file"
  for link in $(getlinks "$file" | uniq); do
    escapedlink=$(sed 's/\[/\\\[/g; s/\]/\\\]/g;' <<< $link)
    dedupe "$escapedlink" "$file" #&& echo "deduped $link in $file" >&2
  done
  sed -i ':a; /^\n*$/{$d; N; ba; }' "$file" #&& echo "removed trailing empty lines in $file" >&2
done
