#!/bin/bash
# Function to handle errors
handle_error() {
    local exit_code=$1
    local message=$2
    echo "Error: $message"
    exit "$exit_code"
}

# Usage
if [ $# -lt 0 ]; then
    handle_error 1 "Usage: $0 <opt: loop>"
fi

crosslink_all_files() {
  for file in $(find "$OBSIDIANDIRECTORY" -type f -name "*.md"); do
    crosslink "$file"
    for link in $(getlinks "$file" | uniq); do
      escapedlink=$(sed 's/\[/\\\[/g; s/\]/\\\]/g;' <<< $link)
      dedupe "$escapedlink" "$file" #&& echo "deduped $link in $file" >&2
    done
    sed -i ':a; /^\n*$/{$d; N; ba; }' "$file" #&& echo "removed trailing empty lines in $file" >&2
  done
}

crosslink_all_files

if [ "$1" == "loop" ];
then
  notify-send "not functional"
  exit
  ## Wait for a write operation on any .md file in the directory
  #inotifywait -e modify -m "$OBSIDIANDIRECTORY/.obsidian/workspace.json" -q | while read file; do
    #notify-send "workspace.json modified"
    #crosslink_all_files; notify-send "crosslinking al files"
  #done
  
  #while true; do
    ##inotifywait -e modify "$OBSIDIANDIRECTORY/.obsidian/workspace.json" && crosslink_all_files && notify-send "success"
    #inotifywait -e modify "$OBSIDIANDIRECTORY/.obsidian/workspace.json" && notify-send "workspace changed"
  #done
fi
