#!/bin/bash
# Function to handle errors
handle_error() {
    local exit_code=$1
    local message=$2
    echo "Error: $message"
    exit $exit_code
}

last_command=$(tail -1 ~/.bash_history)
echo $last_command >> $HOME/.neatcommands
echo "Added $last_command to \$HOME/.neatcommands"
