#!/bin/bash

# Ensure a repo is provided
if [ $# -lt 1 ]; then
    handle_error 1 "Usage: $0 <repo name>"
fi

git init
git add .
git commit -m 'first commit'
git branch -M main
git remote add origin https://github.com/benz1234567/$1.git
git push -u origin main
