#!/bin/bash
# Function to handle errors
handle_error() {
    local exit_code=$1
    local message=$2
    echo "Error: $message"
    exit $exit_code
}

# Usage
#if [ $# -lt 1 ]; then
    #handle_error 1 "Usage: $0 <>"
#fi

# Check if stdin is empty
#if [ -t 0 ]; then
    #echo "Error: No input provided on stdin" >&2
    #exit 1
#fi

# dir="$(find . -type d | dmenu -c -i -l 20)"
st -c "floating" -g 100x30 -e sh -c '.fuzzyscript' 2>/dev/null

[ $(cat /tmp/pj | wc -l) -lt 1 ] && echo "/home/benny" > "$HOME/.projdir" && exit
dir=$(cat "/tmp/pj")
[ "$dir" == "~" ] && dir="/home/benny"
cd "$dir"
echo $(pwd) > $HOME/.projdir
rm -f /tmp/pj
