#!/bin/bash
# Function to handle errors
handle_error() {
    local exit_code=$1
    local message=$2
    echo "Error: $message"
    exit $exit_code
}

# Usage
#if [ $# -lt 1 ]; then
    #handle_error 1 "Usage: $0 <>"
#fi

# Check if stdin is empty
#if [ -t 0 ]; then
    #echo "Error: No input provided on stdin" >&2
    #exit 1
#fi

id=$(xinput | grep 'ELAN071A:00 04F3:30FD Mouse' | grep -o 'id=[0-9]\+' | grep -o '[0-9]\+')

isenabled=$(xinput list-props 10 | grep 'Device Enabled' | awk '{print $4}')

[ "$isenabled" == 1 ] && xinput set-prop "$id" 'Device Enabled' 0 || xinput set-prop "$id" 'Device Enabled' 1

